import type {
  BenchmarkCellRecord,
  BenchmarkEventRecord,
  BenchmarkRunRecord,
} from "@/lib/benchmarks/types";

const now = new Date().toISOString();
const runId = "7b55e4d1-0833-4fb6-a5f3-94684095ff8e";

export const sampleRuns: BenchmarkRunRecord[] = [
  {
    id: runId,
    status: "completed",
    suiteIds: ["swe-bench-verified", "terminal-bench-2.1", "tau2-telecom"],
    harnesses: ["claude-code", "codex", "opencode", "eve", "mastra"],
    taskLimit: 3,
    maxConcurrency: 10,
    cellCount: 15,
    completedCellCount: 13,
    failedCellCount: 2,
    createdAt: now,
    updatedAt: now,
    completedAt: now,
  },
];

export const sampleCells: BenchmarkCellRecord[] = [
  {
    id: "c45e7227-a348-4afb-bf07-e4f53544e501",
    runId,
    suiteId: "swe-bench-verified",
    suiteName: "SWE-bench Verified",
    taskId: "swe-bench-verified-task-001",
    taskTitle: "SWE-bench Verified seed task 1",
    harnessId: "claude-code",
    modelId: "opus-4.8",
    modelName: "claude-opus-4-8",
    modelProvider: "anthropic",
    modelConfig: {
      id: "opus-4.8",
      provider: "anthropic",
      model: "claude-opus-4-8",
      apiKeyEnv: "ANTHROPIC_API_KEY",
    },
    status: "completed",
    sandboxId: "sbx_sample_01",
    commandId: "cmd_sample_01",
    score: 88.6,
    passed: true,
    durationMs: 732_000,
    tokenUsage: { input: 81234, output: 12490 },
    costEstimate: 4.18,
    logs: "Sample completed run.",
    artifacts: [
      { label: "result.json", kind: "json", path: "/workspace/result.json" },
    ],
    error: null,
    rawHarnessResult: { sample: true },
    createdAt: now,
    updatedAt: now,
    completedAt: now,
  },
  {
    id: "0a7f238f-5ad6-4191-b53c-216cd57881f6",
    runId,
    suiteId: "swe-bench-verified",
    suiteName: "SWE-bench Verified",
    taskId: "swe-bench-verified-task-001",
    taskTitle: "SWE-bench Verified seed task 1",
    harnessId: "codex",
    modelId: "gpt-5.5",
    modelName: "gpt-5.5",
    modelProvider: "openai",
    modelConfig: {
      id: "gpt-5.5",
      providerId: "openai",
      model: "gpt-5.5",
      apiKeyEnv: "OPENAI_API_KEY",
      codexProviderMode: "openai",
      wireApi: "responses",
    },
    status: "completed",
    sandboxId: "sbx_sample_02",
    commandId: "cmd_sample_02",
    score: 82.6,
    passed: true,
    durationMs: 690_000,
    tokenUsage: { input: 76220, output: 11810 },
    costEstimate: 3.71,
    logs: "Sample completed run.",
    artifacts: [
      { label: "result.json", kind: "json", path: "/workspace/result.json" },
    ],
    error: null,
    rawHarnessResult: { sample: true },
    createdAt: now,
    updatedAt: now,
    completedAt: now,
  },
  {
    id: "24e90f4f-c6ce-4125-a756-314e29ad2811",
    runId,
    suiteId: "terminal-bench-2.1",
    suiteName: "Terminal-Bench 2.1",
    taskId: "terminal-bench-2.1-task-001",
    taskTitle: "Terminal-Bench 2.1 seed task 1",
    harnessId: "opencode",
    modelId: "sonnet-opencode",
    modelName: "anthropic/claude-sonnet",
    modelProvider: "anthropic",
    modelConfig: {
      id: "sonnet-opencode",
      provider: "anthropic",
      model: "anthropic/claude-sonnet",
      apiKeyEnv: "ANTHROPIC_API_KEY",
    },
    status: "completed",
    sandboxId: "sbx_sample_03",
    commandId: "cmd_sample_03",
    score: 74.1,
    passed: true,
    durationMs: 518_000,
    tokenUsage: { input: 40110, output: 9012 },
    costEstimate: 1.92,
    logs: "Sample completed run.",
    artifacts: [
      { label: "result.json", kind: "json", path: "/workspace/result.json" },
    ],
    error: null,
    rawHarnessResult: { sample: true },
    createdAt: now,
    updatedAt: now,
    completedAt: now,
  },
  {
    id: "252a70e7-2a7d-463a-8dc8-37836d607812",
    runId,
    suiteId: "tau2-telecom",
    suiteName: "Tau2-bench Telecom",
    taskId: "tau2-telecom-task-001",
    taskTitle: "Tau2-bench Telecom seed task 1",
    harnessId: "mastra",
    modelId: "mastra-gpt",
    modelName: "vercel/openai/gpt-5.5",
    modelProvider: "vercel",
    modelConfig: {
      id: "mastra-gpt",
      provider: "vercel",
      model: "vercel/openai/gpt-5.5",
      apiKeyEnv: "OPENAI_API_KEY",
    },
    status: "completed",
    sandboxId: "sbx_sample_04",
    commandId: "cmd_sample_04",
    score: 91.3,
    passed: true,
    durationMs: 348_000,
    tokenUsage: { input: 21190, output: 6200 },
    costEstimate: 1.36,
    logs: "Sample completed run.",
    artifacts: [
      { label: "result.json", kind: "json", path: "/workspace/result.json" },
    ],
    error: null,
    rawHarnessResult: { sample: true },
    createdAt: now,
    updatedAt: now,
    completedAt: now,
  },
];

export const sampleEvents: BenchmarkEventRecord[] = [
  {
    id: "269e188d-4d38-4fce-aa57-cd725fbd336f",
    runId,
    cellId: null,
    type: "run.completed",
    message: "Sample benchmark run completed.",
    payload: { sample: true },
    createdAt: now,
  },
];
